// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Carousel from "stimulus-carousel"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CoachController from "./coach_controller"
application.register("coach", CoachController)

import PriceController from "./price_controller"
application.register("price", PriceController)


application.register('carousel', Carousel)
